# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags: ["v*"]  # 仅当推送v开头的标签时触发（如v1.0.0）
  workflow_dispatch:  # 支持手动触发

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Go mod
      run: go mod tidy
    
    - name: Build 
      run: ./build.sh
      


    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动使用内置Token
      with:
        files: |
          out/*.deb
        tag_name: ${{ github.ref_name }}  # 使用触发工作流的标签（如v1.0.0）
        name: " AssisMgr Release ${{ github.ref_name }}"
        body: |
          自动化构建的应用服务，包含以下文件：
          - assismgr linux amd64 
          - assismgr linux arm64 

          * 版本: ${{ github.ref_name }}
          * Commit: ${{ github.sha }}
          * 提交信息: ${{ github.event.head_commit.message }}
          * 提交者: ${{ github.event.head_commit.author.name }}

          * 安装运行：
          ```bash
          sudo dpkg -i assismgr_v${{ github.ref_name }}_amd64.deb 
          sudo systemctl start assismgr
          ```
        draft: false  # 直接发布，非草稿模式
